<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;
use App\Models\Edu;
use App\Models\Project;
use App\Models\User;

// ✅ Smart homepage route
Route::get('/', function () {

    return view('home', [
        'user' => User::with('skills')->first(),
        'education' => Edu::all(),
        'projects' => Project::all()
    ]);
});

// ✅ Portfolio routes
Route::get('/about', function () {
    return view('about', [
        'user' => User::first()
    ]);
});

Route::get('/contact', function () {
    return view('contact', [
        'user' => User::first()
    ]);
});

Route::get('/education', function () {
    return view('education', [
        'education' => Edu::all(),
        'user' => User::first()
    ]);
});

Route::get('/projects', function () {
    return view('projects', [
        'projects' => Project::all()
    ]);
});

Route::get('/temp', function () {
    return view('temp');
});

// ✅ Breeze routes
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// ✅ Auth routes generated by Breeze
require __DIR__.'/auth.php';
